### ISSUE TITLE
Sous-Section XML JATS

### ISSUE THREAD

**Issue by PookMook** [EcrituresNumeriques/transformation_jats_erudit#1]
"J'aimerais savoir comment sont représentées les sous-sections de deuxième et troisième niveaux dans les artéfacts produits par Stylo."

**Comment by PookMook** [comment]
J'ai mis un exemple de texte qui sort directement de stylo : 
https://github.com/EcrituresNumeriques/transformation_jats_erudit/blob/master/jats/sous-section.xml

toute la partie <front></front> est encore générée à la main (en attendant de pouvoir la faire dans stylo) mais tu peux voir comment sont générés les sections/sous-sections.

**Comment by petithobbit** [comment]
Merci. Cela m'a été utile.
